[CS_Hud]
Credits1="GT INTERACTIVE"
Credits2="LEGEND ENTERTAINMENT"
; EN: Credits3="AND EPIC GAMES"
Credits3="ET EPIC GAMES"
; EN: Credits4="PRESENT"
Credits4="PRESENTENT"
; EN: GameTitle="UNREAL: RETURN TO NA PALI"
GameTitle="UNREAL: RETURN TO NA PALI"
